### ISSUE TITLE
Update to libxl 3.5.4.1

### ISSUE THREAD

**Issue by ghost** [qustavo/libxlpy#2]
Do you plan to update your code to actual version of libxl (3.5.4.1) soon?

**Comment by qustavo** [comment]
Not yet, sorry. The last working version is ftp://xlware.com/libxl-lin-3.5.3.tar.gz. But contributions are welcomed :smiley:.

**Comment by ghost** [comment]
Ok will (and must :) ) do. Must close project before. Will start in 2 Weeks.

**Comment by qustavo** [comment]
:+1:

**Comment by ghost** [comment]
Done.
